[package]
name = "orc-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
orc-bridge.workspace = true
ratatui.workspace = true
crossterm.workspace = true
tokio.workspace = true
anyhow.workspace = true
serde_json.workspace = true
notify.workspace = true
helix-core = { git = "https://github.com/helix-editor/helix" }
