[package]
name = "orc-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
orc-api.workspace = true
orc-auth.workspace = true
orc-config.workspace = true
orc-tools.workspace = true
orc-permissions.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true
uuid.workspace = true
chrono.workspace = true
futures.workspace = true
